### ISSUE TITLE
Move away from Heroku

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/prism#318]
Heroku is an amazing platform and has served this project well over the years. However, they are now shifting their pricing model (https://blog.heroku.com/archives/2015/5/7/new-dyno-types-public-beta). Because of state bureaucracy, we can't purchase services from them in this new model, and we need to have a discussion on what to do next.

There are a few options I see:
1. Shut it down. It's been a good run, but there hasn't been active development of any significant new features in the last two years. This makes is a maintenance project with diminishing returns. There is still quite a bit of use of the tool from the K-12 folks, but this still hasn't spurred much activity as time constraints and life in general get in the way. An option worth discussing further.
2. Deploy this application to another service. [appfog](https://www.appfog.com/) and [openshift](https://www.openshift.com/) both provide a free tier. However, each of these has some constraints which would need to be considered in a migration.
3. Community sponsorship...some of you all have real jobs now. 

There are probably others (which I'd love to hear), but wanted to start a discussion before this comes crashing down and the service just goes away.

Wayne

**Comment by drosboro** [comment]
I'm interested in helping with option #3.  Depending on current traffic levels, I may be able to help with hosting with my existing servers.  I've sent you an email to discuss further.

**Comment by bmw9t** [comment]
Closed b/c we've moved to Capistrano, which, as I understand it, is meant to address this.
