### ISSUE TITLE
My Prism's error

### ISSUE THREAD

**Issue by mamarobertson4** [scholarslab/prism#319]
HI all,
 I use Prism quite frequently and the Myprisms portal isn't working. I was also sad to see that this service might be going away which would be a real loss for teachers like me in k-12 world. I've actually presented on using Prism at ERB and at the BLC conference in Boston. I know lots of folks who would love to help in some way. Please feel free to get in touch! Thanks, Laura Robertson

**Comment by bmw9t** [comment]
Thanks so much for pointing this out, Laura! I just sent out a fix that should take care of it, and I fixed up the page while I was at it to make a bit more flexible. And thanks so much for continuing to advocate for Prism! The significant use by K-12 teachers has been very exciting. And we'll definitely keep your kind offer in mind as we figure out the future of Prism in the coming months.
