### ISSUE TITLE
Upgrade OmniAuth Facebook

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/prism#328]
Facebook GraphAPI is removing support for the Graph API calls < v2.1. The version of `facebook-omniauth` that is currently in place makes calls to the v2.0 API and will no longer work after August 8, 2016. I _think_ this should be just as easy as upgrading the gem (it's currently at v3.0.0) and updating the callback in the initializers (http://www.rubydoc.info/gems/omniauth-facebook/3.0.0). 

The other (easier) option is to just remove support for Facebook authentication...

**Comment by bmw9t** [comment]
Haven't looked in detail, but it looks like upgrading facebook-omniauth will also require upgrading omni-auth-oauth2 as a dependency. Which would probably involve tweaks to the other omniauth logins as well:

From my bundler just now:

Bundler could not find compatible versions for gem "omniauth-oauth2":
  In snapshot (Gemfile.lock):
    omniauth-oauth2 (= 1.1.2)

  In Gemfile:
    omniauth-oauth2 (~> 1.1.2)

    omniauth-facebook (~> 3.0.0) was resolved to 3.0.0, which depends on
      omniauth-oauth2 (~> 1.2)

    omniauth-google-oauth2 was resolved to 0.2.8, which depends on
      omniauth-oauth2 (>= 1.1.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by bmw9t** [comment]
Check back in August 8th to make sure that it outlasts the old facebook API being deprecated.

**Comment by bmw9t** [comment]
Yep - still working.

**Comment by erochest** [comment]
Thank you for checking!
