### ISSUE TITLE
Classroom users

### ISSUE THREAD

**Issue by Mpini** [scholarslab/prism#334]
Love your product.  Would like to use it with students that do not have an email address.  Could you configure it to accept a class code, so that younger students do not need to input an email.

Thank you for your consideration!

**Comment by walshbr** [comment]
Hello! We don't officially have the functionality built in, and we also are not actively developing the tool to be able to implement it. But you're not the first one to ask. There's actually a known workaround though - Prism doesn't check whether your emails are real. It just looks to make sure they look like emails. So I was able to successfully create an account with this:

username: notarealemail@fake.com
password: fakepassword

As you may have guessed, it is not a real email. So you should be able to fake your way through the system for the students. I might just invent your own classroom codes by giving each student an email and login (you could set them up yourself or just have them log in). Something like:

mpini1@class.com, mpini2@class.com, mpini3@class.com
with your own passwords to match.

Not the most elegant, but it should let you do what you want to do. Hope this helps!

**Comment by Mpini** [comment]
Thank you!


Marguerite Pini
St. Vincent de Paul School
Co-Principal

2350 Green St.
San Francisco, CA 94123
Telephone (415) 346-5505
Fax (415)346-0970

“ We cannot do great things on this Earth, only small things with great love.” -Saint Mother Teresa

The contents of this message are privileged and confidential. This message should not be forwarded or distributed without the permission of the author.

________________________________
